name: "Deploy to proxy.servers.hackclub.com"

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout hackclub/proxy"
        uses: actions/checkout@v2.3.4
      - name: "Install Nix"
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Install SSH key for deployment"
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: "Set known host info for proxy.servers.hackclub.com"
        run: echo "proxy.servers.hackclub.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFkAeRX+PZlYApsNZZegjtN+fgafz8Kd85hUa93T2HYn" >> ~/.ssh/known_hosts
      - name: "Build and deploy to proxy.servers.hackclub.com"
        run: ./deploy
