# Note: Proxy does not have a test suite, this just checks to see if the
# deployment will build to catch any compile-time errors.
name: "Check for syntax and configuration errors"

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout hackclub/proxy"
        uses: actions/checkout@v2.3.4
      - name: "Install Nix"
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: "Enable nix-command experimental feature (needed for Morph)"
        run: mkdir -p ~/.config/nix && echo "experimental-features = nix-command" >> ~/.config/nix/nix.conf
      - name: "Build the deployment to see if there are any syntax or configuration errors that can be caught at compile time"
        run: nix-shell -p morph --run "morph build network.nix"
